[package]
name = "RayMarching_FPS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "*"
sdl2 = "*"
cgmath = "0.18.0"
image = "*"
rand = "0.8"