[package]
name = "rmgl_demo"
version = "1.0.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmgl = { path = "../rmgl" }
gl = "0.14"
sdl2 = "0.36"
rand = "0.8"